src/AlertSense.Pine.Website/Controllers/GamesController.cs
using AlertSense.Pine.Requests;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlertSense.Pine.Website.Controllers
{
    public class GamesController : Controller
    {
        public ActionResult Index()
        {
            var games = MvcApplication.Api.GetAllGames();

            return View(games);
        }

        public ActionResult Create()
        {
            var players = MvcApplication.Api.GetAllPlayers();

            ViewBag.Players = players.Select(x => new SelectListItem { Text = string.Format("{0} {1}", x.FirstName, x.LastName), Value = x.Id.ToString()});

            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateGameRequest request)
        {
            try
            {
                var gameModel = MvcApplication.Api.StartNewGame(request);

                return RedirectToAction("Edit", new { id = gameModel.Id });
            }
            catch
            {
                return View(request);
            }
        }

        public ActionResult Edit(int id)
        {
            var gameModel = MvcApplication.Api.GetGame(id);

            if (gameModel.CompletedTime != DateTime.MinValue)
                return RedirectToAction("Details", new { id = gameModel.Id });

            return View(gameModel);
        }

        [HttpPost]
        public ActionResult Edit(CompletedGameRequest request)
        {
            try
            {
                var gameModel = MvcApplication.Api.CompleteGame(request);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(request);
            }
        }

        public ActionResult Details(int id)
        {
            var gameModel = MvcApplication.Api.GetGame(id);

            if (gameModel.CompletedTime == DateTime.MinValue)
                return RedirectToAction("Edit", new { id = gameModel.Id });

            return View(gameModel);
        }
    }
}

src/AlertSense.Pine.Website/Controllers/PlayersController.cs
using AlertSense.Pine.Models;
using AlertSense.Pine.Requests;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceStack;

namespace AlertSense.Pine.Website.Controllers
{
    public class PlayersController : Controller
    {
        public ActionResult Index()
        {
            return View(MvcApplication.Api.GetAllPlayers());
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(CreatePlayerRequest request)
        {
            try
            {
                var playerModel = MvcApplication.Api.CreatePlayer(request);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(request);
            }
        }

        public ActionResult Edit(int id)
        {

            var playerModel = MvcApplication.Api.GetPlayer(id);

            return View(playerModel.ConvertTo<CreatePlayerRequest>());
        }

        [HttpPost]
        public ActionResult Edit(CreatePlayerRequest request)
        {
            try
            {
                var playerModel = MvcApplication.Api.CreatePlayer(request);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(request);
            }
        }

        public ActionResult Details(int id)
        {
            var playerModel = MvcApplication.Api.GetPlayer(id);

            return View(playerModel);
        }
    }
}

src/AlertSense.Pine.Website/Views/Games/Create.cshtml
@model AlertSense.Pine.Requests.CreateGameRequest

@{
    ViewBag.Title = "Create";
}

<h2>Start New Game</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Select the oponents</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.PlayerIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PlayerIds, (IEnumerable<SelectListItem>)ViewBag.Players, new { @class = "form-control", multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.PlayerIds, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/AlertSense.Pine.Website/Views/Games/Details.cshtml
@model AlertSense.Pine.Models.CompletedGameModel

@{
    ViewBag.Title = "Details";
}

<h2>Game Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>
    </dl>

    <table class="table">
        <tr>
            <th>Name</th>
            <th>Score</th>
        </tr>
        @{
            int index = 0;
            foreach (var player in Model.PlayersScores)
            {
                <tr>
                    <td>@string.Format("{0} {1}", player.FirstName, player.LastName)</td>
                    <td>
                        @player.Score.ToString()
                    </td>
                </tr>
            }
        }
    </table>
</div>
<p>
    @Html.ActionLink("View Game History", "Index")
</p>

src/AlertSense.Pine.Website/Views/Games/Edit.cshtml
@model AlertSense.Pine.Models.CompletedGameModel

@{
    ViewBag.Title = "Details";
}

<h2>Game Details</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.Id)
        <h4>Select the oponents</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.StartTime, new { @class = "form-control" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Complete Game" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/AlertSense.Pine.Website/Views/Games/Index.cshtml
@model IEnumerable<AlertSense.Pine.Models.CompletedGameModel>

@{
    ViewBag.Title = "View";
}

<h2>Games</h2>

<p>
    @Html.ActionLink("Start New Game", "Create")
</p>
<table class="table">
    <tr>
        <th>Start Time</th>
        <th>Completed Time</th>
        <th>Players</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.StartTime.ToString(), (item.CompletedTime == DateTime.MinValue ? "Edit" : "Details"), "Games", new { id = item.Id }, null)
            </td>
            <td>
                @(item.CompletedTime == DateTime.MinValue ? "Incomplete" : item.CompletedTime.ToString())
            </td>
            <td>
                <ul>
                    @foreach (var playerScore in item.PlayersScores)
                    {
                        <li>@Html.ActionLink(string.Format("{0} {1}", playerScore.FirstName, playerScore.LastName), "Edit", "Players", new { id = item.Id }, null)</li>
                    }
                </ul>

            </td>
        </tr>
    }

</table>